# Location of top-level MicroPython directory
MPY_DIR = ../../micropython

# Name of module
MOD = eml_trees

# Source files (.c or .py)
SRC = trees.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
ARCH = x64

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
