
include("$(PORT_DIR)/variants/manifest.py")

# emlearn .py modules
module("emlearn_trees.py", base_path='./emlearn_trees')
module("emlearn_fft.py", base_path='./emlearn_fft')
module("emlearn_linreg.py", base_path='./emlearn_linreg')

# The following are expected by pyscript
# Ref https://github.com/micropython/micropython/blob/master/ports/webassembly/variants/pyscript/manifest.py
require("abc")
require("base64")
require("collections")
require("collections-defaultdict")
require("copy")
require("datetime")
require("fnmatch")
require("functools")
require("gzip")
require("hmac")
require("html")
require("inspect")
require("io")
require("itertools")
require("locale")
require("logging")
require("operator")
require("os")
require("os-path")
require("pathlib")
require("stat")
require("tarfile")
require("tarfile-write")
require("time")
require("unittest")
require("uu")
require("zlib")
